export enum ApplicationStatus {
  PREAPPROVAL = 'PREAPPROVAL',
  APPROVED = 'APPROVED',
  CC_DENIED = 'CC_DENIED',
  CC_APPROVED = 'CC_APPROVED',
  PREPARE_DOCUMENTS = 'PREPARE_DOCUMENTS',
  DOCUMENT_CREATED = 'DOCUMENT_CREATED',
  CLIENT_DENIED = 'CLIENT_DENIED',
  DOCUMENT_SIGNED = 'DOCUMENT_SIGNED',
  CREDIT_ISSUED = 'CREDIT_ISSUED',
}
